baseURL = "https://erykgrabkowski.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Eryk Grabkowski"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
   name = "Eryk Grabkowski"
   headline = "Hello! I'm Eryk Grabkowski, a recent IT graduate living in Ireland. I work as a Network Operations Centre Technician."
   image = "author.jpg"  # path relative to static directory

  links = [
    { email1 = { href = "mailto:eryk@grabkowski.net", text = "@ Email Address" } },
    { linkedin = "https://linkedin.com/in/erykgrabkowski" },
    { github = "https://github.com/erykgrabkowski" },
    # { youtube = "https://youtube.com/" },
    # { twitter = "https://twitter.com/" },
    # { discord = "https://discord.gg/" },
    # { instagram = "https://instagram.com/" },
    # { tiktok = "https://tiktok.com/" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { whatsapp = "https://wa.me/phone-number" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"